from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome(r"C:\Users\chintu\PycharmProjects\FirstSeleniumTest\drivers\chromedriver.exe")

driver.set_page_load_timeout(10)
driver.get("https://www.google.com/ ")
driver.find_element_by_name("q").send_keys("Rediffmail")
driver.maximize_window()
driver.find_element_by_name("btnK").send_keys(Keys.ENTER)
a1=driver.find_element_by_class_name("LC20lb")
a1.click()
a2=driver.find_element_by_name("login")
a2.send_keys("Priyad.pk@rediffmail.com")
a3=driver.find_element_by_name("passwd")
a3.send_keys("ilovemyself")
a4=driver.find_element_by_name("proceed")
a4.click()
time.sleep(4)
a5=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[1]/ul/li[1]/a")
a5.click()
#driver.find_element_by_.send_keys("chaitanyavsml@gmail.com")
s1=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[1]/ul/li[3]/a")
s1.click()
time.sleep(3)
s2=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[1]/ul/li[4]/a")
s2.click()
time.sleep(3)
s3=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[1]/ul/li[5]/a")
s3.click()
time.sleep(3)
s4=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[1]/ul/li[6]/a")
s4.click()
time.sleep(3)
s5=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[1]/ul/li[7]/a")
s5.click()
time.sleep(3)
a6=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[1]/ul/li[9]/a")
a6.click()
time.sleep(2)
driver.find_element_by_class_name("addfolder_txtbox").send_keys("Automation")
a7=driver.find_element_by_id("folder_submit")
a7.click()
time.sleep(4)
a8=driver.find_element_by_xpath("/html/body/div[27]/div[2]/form/div[2]/div/div[3]/button")
a8.click()
time.sleep(6)
d1=driver.find_element_by_class_name("rd_personal_link")
d1.click()
time.sleep(3)
s1=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[1]/ul/li[8]/ul/li/a/b")
s1.click()
time.sleep(3)
s2=driver.find_element_by_xpath("/html/body/div[27]/div[2]/form/div[2]/div/div[3]/button[1]")
s2.click()
time.sleep(3)
s3=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/h4")
s3.click()
time.sleep(3)
s4=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div[7]/div/div[3]/div/div[2]/ul/li[2]/a")
s4.click()
time.sleep(3)
s5=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div[7]/div/div[3]/div/div[2]/ul/li[3]/a")
s5.click()
s6=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/h4")
s6.click()
time.sleep(3)
s7=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div[6]/div/div[1]/div[1]")
s7.click()
s8=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div[6]/div/div[5]/div[1]/div[3]/input")
s8.send_keys("   Automation testing on Rediffmail")
driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div[6]/div/div[5]/div[1]/div[5]/input").send_keys("AISSMS IOIT")
time.sleep(3)
q1=driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div[6]/h4/span")
q1.click()
time.sleep(3)
q2=driver.find_element_by_xpath("/html/body/div[4]/div[1]/div/div[2]/a[2]")
q2.click()
time.sleep(4)
driver.quit()
print("Test is completed successfully")


